import { Component } from '@angular/core';

@Component({
    selector: 'app-admin-boosts-boost',
    templateUrl: 'boost.component.html',
    styleUrls: ['boost.component.css'],
})
export class BoostComponent {
    sources: Array<{ value: string; label: string }> = [
        { label: 'TC', value: 'Trade Chat' },
        { label: 'TCL', value: 'Ticket Client' },
        { label: 'TIH', value: 'Ticket In-house' },
        { label: 'D', value: 'Discord' },
    ];
    payments: Array<{ amount: number; realm: string }> = [
        {
            amount: 0,
            realm: '',
        },
    ];
    keys: Array<{ key: string; userId?: string; role?: string }> = [
        {
            key: '',
            userId: '',
            role: '',
        },
    ];
    dungeons = [
        { label: 'Any', value: 'Any' },
        { label: 'De Other Side', value: 'DOS' },
        { label: 'Halls of Atonement', value: 'HOA' },
        { label: 'Mists of Tirna Scithe', value: 'MISTS' },
        { label: 'Plaguefall', value: 'PLAGUE' },
        { label: 'Sanguine Depths', value: 'SD' },
        { label: 'Spires of Ascension', value: 'SD' },
        { label: 'The Necrotic Wake', value: 'TNW' },
        { label: 'Theater of Pain', value: 'TOP' },
        { label: 'Tazavesh the Veiled Market', value: 'TAZ' },
    ];
    armorStacks = [
        { label: 'Any', value: 'Any' },
        { label: 'Leather', value: 'Leather' },
        { label: 'Plate', value: 'Plate' },
        { label: 'Mail', value: 'Mail' },
        { label: 'Cloth', value: 'Cloth' },
    ];
    classStacks = [
        { label: 'Any', value: 'Any' },
        { label: 'Warrior', value: 'Warrior' },
        { label: 'Paladin', value: 'Paladin' },
        { label: 'Hunter', value: 'Hunter' },
        { label: 'Rogue', value: 'Rogue' },
        { label: 'Priest', value: 'Priest' },
        { label: 'Shaman', value: 'Shaman' },
        { label: 'Mage', value: 'Mage' },
        { label: 'Warlock', value: 'Warlock' },
        { label: 'Monk', value: 'Monk' },
        { label: 'Druid', value: 'Druid' },
        { label: 'Demon Hunter', value: 'Demon Hunter' },
        { label: 'Death Knight', value: 'Death Knight' },
    ];
    roles = [
        { label: 'Tank', value: 'Tank' },
        { label: 'Healer', value: 'Healer' },
        { label: 'DPS', value: 'DPS' },
    ];

    isChecked: boolean = false;

    amount: number;
    totalPot: number = 0;
    discount: number;

    realms = [
        'AeriePeak',
        'Aggra',
        'Aggramar',
        'Alonsus',
        'Anachronos',
        'Arathor',
        'Aszune',
        'Azjol-Nerub',
        'Azuremyst',
        "Blade'sEdge",
        'Bloodhoof',
        'Bronzebeard',
        'BronzeDragonflight',
        'ChamberofAspects',
        'Darkspear',
        'Doomhammer',
        'Draenor',
        'Dragonblight',
        'Eonar',
        'Ghostlands',
        'Hellfire',
        'Hellscream',
        'Khadgar',
        'Kilrogg',
        'KulTiras',
        'Lightbringer',
        'Nagrand',
        'Nordrassil',
        "Quel'Thalas",
        'Runetotem',
        'Saurfang',
        'Shadowsong',
        'Silvermoon',
        'Stormrage',
        'Terenas',
        'Terokkar',
        'Thunderhorn',
        'Turalyon',
        "Vek'nilash",
        'Wildhammer',
        'Agamaggan',
        "Al'Akir",
        "Ahn'Qiraj",
        'Auchindoun',
        'Balnazzar',
        'Bladefist',
        'Bloodfeather',
        'Bloodscalp',
        'Boulderfist',
        'BurningBlade',
        'BurningLegion',
        'BurningSteppes',
        'Chromaggus',
        'Crushridge',
        'Daggerspine',
        'Darksorrow',
        'Deathwing',
        'Dentarg',
        'Dragonmaw',
        "Drak'thul",
        'Dunemaul',
        'Emeriss',
        'Executus',
        'Frostmane',
        'Frostwhisper',
        'Genjuros',
        'GrimBatol',
        'Haomarush',
        'Hakkar',
        'Jaedenar',
        'Karazhan',
        'Kazzak',
        "Kor'gall",
        'LaughingSkull',
        "Lightning'sBlade",
        'Magtheridon',
        'Mazrigos',
        'Neptulon',
        'Outland',
        'Ragnaros',
        'Ravencrest',
        'ShatteredHalls',
        'ShatteredHand',
        'Skullcrusher',
        'Spinebreaker',
        'Stormreaver',
        'Stormscale',
        'Sunstrider',
        'Sylvanas',
        'Talnivarr',
        'TarrenMill',
        'TheMaelstrom',
        'Trollbane',
        "Twilight'sHammer",
        'TwistingNether',
        'Vashj',
        'Xavius',
        'Zenedar',
        'ArgentDawn',
        'DarkmoonFaire',
        'EarthenRing',
        'Moonglade',
        'SteamwheedleCartel',
        "TheSha'tar",
        'DefiasBrotherhood',
        'Ravenholdt',
        'ScarshieldLegion',
        'Sporeggar',
        'TheVentureCo',
        'Chantséternels',
        'Dalaran',
        "Drek'Thar",
        'Eitrigg',
        'Elune',
        'Hyjal',
        'KhazModan',
        'Krasus',
        'MarécagedeZangar',
        'Medivh',
        'Suramar',
        'Uldaman',
        "Vol'jin",
        'Arak-arahm',
        'Arathi',
        'Archimonde',
        "Cho'gall",
        "Eldre'Thalas",
        'Garona',
        'Illidan',
        "Kael'Thas",
        'Naxxramas',
        "Ner'zhul",
        'Rashgarroth',
        'Sargeras',
        'Sinstralis',
        'Templenoir',
        "Throk'Feroth",
        'Varimathras',
        'Ysondre',
        'ConfrérieduThorium',
        'KirinTor',
        'LesClairvoyants',
        'LesSentinelles',
        'ConseildesOmbres',
        'CultedelaRiveNoire',
        'LaCroisadeécarlate',
        'Alexstrasza',
        'Alleria',
        "Aman'Thul",
        'Ambossar',
        'Antonidas',
        'Area52',
        'Arygos',
        'Baelgun',
        'Blackhand',
        'DunMorogh',
        'Durotan',
        'Gilneas',
        'Kargath',
        "Khaz'goroth",
        'Lordaeron',
        'Lothar',
        'Madmortem',
        'Malfurion',
        'Malygos',
        'Nethersturm',
        'Norgannon',
        'Nozdormu',
        'Perenolde',
        'Proudmoore',
        'Rexxar',
        "Sen'jin",
        'Shattrath',
        'Teldrassil',
        'Thrall',
        'Tirion',
        'Ysera',
        'Aegwynn',
        'Anetheron',
        "Anub'arak",
        'Arthas',
        'Azshara',
        'Blackmoore',
        'Blackrock',
        'Blutkessel',
        'Dalvengyr',
        'Destromath',
        'Dethecus',
        'Echsenkessel',
        'Eredar',
        'FestungderStürme',
        'Frostmourne',
        'Frostwolf',
        'Gorgonnash',
        "Gul'dan",
        "Kel'Thuzad",
        "Kil'Jaeden",
        "Krag'jin",
        "Mal'Ganis",
        'Mannoroth',
        "Mug'thol",
        'Nathrezim',
        'Nazjatar',
        'Nefarian',
        "Nera'thor",
        'Onyxia',
        'Rajaxx',
        'Taerar',
        'Terrordar',
        'Theradras',
        'Tichondrius',
        "Un'Goro",
        "Vek'lor",
        'Wrathbringer',
        'Zuluhed',
        'DerMithrilorden',
        'DerRatvonDalaran',
        'DieAldor',
        'DieewigeWacht',
        'DieNachtwache',
        'DieSilberneHand',
        'Forscherliga',
        'Todeswache',
        'ZirkeldesCenarius',
        'DasKonsortium',
        'DasSyndikat',
        'DerabyssischeRat',
        'DieArguswacht',
        'DieTodeskrallen',
        'KultderVerdammten',
        'ColinasPardas',
        'Exodar',
        'LosErrantes',
        'Minahonda',
        'Tyrande',
        "C'Thun",
        'DunModr',
        'Sanguino',
        "Shen'dralar",
        'Uldum',
        "Zul'jin",
        'Pozzo',
        'Nemesis',
    ];

    addPaymentRow(): void {
        this.payments.push({ amount: 0, realm: '' });
    }

    removePaymentRow(payment: any): void {
        this.payments = this.payments.filter((item) => item !== payment);
    }

    addKeyRow(): void {
        this.keys.push({
            key: 'Any',
            userId: '543556245437343244',
            role: 'Tank',
        });
    }

    removeKeyRow(key: any): void {
        this.keys = this.keys.filter((item) => item !== key);
    }

    update(payment: any): void {
        console.log(payment);
        // this.payments.find(item => item === payment).amount
    }

    onChange(): void {
        this.totalPot =
            this.amount - ((this.amount * 100) / 100) * this.discount;
    }

    total(): void {
        this.totalPot = this.payments.reduce(
            (sum, current) => sum + current.amount,
            0
        );
    }
}
