name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install front-end
        working-directory: front-end
        run: npm install
        
      - name: Build front-end
        working-directory: front-end
        run: npm run build:prod
        
      - name: Install back-end
        working-directory: back-end
        run: npm install
        
      - name: Build back-end
        working-directory: back-end
        run: npm run build
        
      - name: Combine front-end back-end
        run: |
          mkdir temp
          mv back-end/dist/* temp/
          mv back-end/node_modules temp/
          mv -f front-end/dist/front-end/* temp/public/
        
      - name: Add ecosystem
        run: cp integration/ecosystem.config.js temp/ecosystem.config.js 
          
      - name: Create .env
        run: |
          echo "${{secrets.APPLICATION_URL}}" >> temp/.env
          echo "${{secrets.APPLICATION_PORT}}" >> temp/.env
          echo "${{secrets.DISCORD_CLIENT_ID}}" >> temp/.env
          echo "${{secrets.DISCORD_CLIENT_SECRET}}" >> temp/.env
          echo "${{secrets.DISCORD_GUILD_ID}}" >> temp/.env
          echo "${{secrets.DISCORD_INTENTS}}" >> temp/.env
          echo "${{secrets.DISCORD_OAUTH_LINK}}" >> temp/.env
          echo "${{secrets.DISCORD_SUPER_ADMIN}}" >> temp/.env
          echo "${{secrets.DISCORD_TOKEN}}" >> temp/.env
          echo "${{secrets.MONGODB_DATABASE}}" >> temp/.env
          echo "${{secrets.MONGODB_HOST}}" >> temp/.env
          echo "${{secrets.TOKEN_SECRET}}" >> temp/.env
          
      - name: Stop current site if running
        working-directory: ~/web/production
        run: pm2 stop ecosystem.config.js
      
      - name: Remove current production code
        run: rm -Rf ~/web/production
        
      - name: Move new files to production
        run: mv temp ~/web/production
        
      - name: Start new production
        working-directory: ~/web/production
        run: pm2 start ecosystem.config.js
