name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install front-end
        working-directory: front-end
        run: npm install
        
      - name: Update environment.prod.ts
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "{{APPLICATION_URL}}"
          replace: ${{secrets.APPLICATION_URL}}"
          include: "front-end/src/environments/**"
        
      - name: Build front-end
        working-directory: front-end
        run: npm run build:prod
        
      - name: Install back-end
        working-directory: back-end
        run: npm install
        
      - name: Build back-end
        working-directory: back-end
        run: npm run build
        
      - name: Combine front-end back-end
        run: |
          mkdir temp
          mv back-end/dist/* temp/
          mv back-end/node_modules temp/
          mv -f front-end/dist/front-end/* temp/public/
        
      - name: Add ecosystem
        run: cp integration/ecosystem.config.js temp/ecosystem.config.js 
          
      - name: Create .env
        run: |
          echo "${{secrets.APPLICATION_URL}}" >> temp/.env
          echo "${{secrets.APPLICATION_PORT}}" >> temp/.env
          echo "${{secrets.DISCORD_CLIENT_ID}}" >> temp/.env
          echo "${{secrets.DISCORD_CLIENT_SECRET}}" >> temp/.env
          echo "${{secrets.DISCORD_GUILD_ID}}" >> temp/.env
          echo "${{secrets.DISCORD_INTENTS}}" >> temp/.env
          echo "${{secrets.DISCORD_OAUTH_LINK}}" >> temp/.env
          echo "${{secrets.DISCORD_SUPER_ADMIN}}" >> temp/.env
          echo "${{secrets.DISCORD_TOKEN}}" >> temp/.env
          echo "${{secrets.MONGODB_DATABASE}}" >> temp/.env
          echo "${{secrets.MONGODB_HOST}}" >> temp/.env
          echo "${{secrets.TOKEN_SECRET}}" >> temp/.env
          
      - name: Check if current production exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "/home/ubuntu/web/production/ecosystem.config.js"
          
      - name: Stop current site if existing
        if: steps.check_files.outputs.files_exists == 'true'
        working-directory: /home/ubuntu/web/production
        run: pm2 stop ecosystem.config.js
      
      - name: Remove current production code
        run: rm -Rf /home/ubuntu/web/production
        
      - name: Move new files to production
        run: mv temp /home/ubuntu/web/production
        
      - name: Start new production
        run: |
          cd /home/ubuntu/web/production
          pm2 start ecosystem.config.js
