name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Which version to be created"
        required: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Install front-end
        working-directory: front-end
        run: npm install

      - name: Update environment.prod.ts
        working-directory: front-end/src/environments
        run: sed -i 's@{{APPLICATION_URL}}@${{secrets.PROD_APPLICATION_URL_ONLY}}@g' environment.prod.ts

      - name: Build front-end
        working-directory: front-end
        run: npm run build:prod

      - name: Install back-end
        working-directory: back-end
        run: npm install

      - name: Build back-end
        working-directory: back-end
        run: npm run build

      - name: Combine front-end back-end
        run: |
          mkdir release
          mv back-end/dist/* release/
          mv back-end/package.json release/
          mv back-end/package-lock.json release/
          mv -f front-end/dist/front-end/* release/web/public/
        
      - name: Install release package
        working-directory: release
        run: npm ci --only=prod
          
      - name: Add ecosystem
        run: cp integration/ecosystem.config.js release/ecosystem.config.js
          
      - name: Merge develop -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ github.token }}
          
      - name: Create file
        run: tar -zcvf release.tar.gz release
          
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: ${{github.event.inputs.version}}
          artifacts: release.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.RELEASE_DEPLOY_DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Web release v${{github.event.inputs.version}} have been successful'
      
